worker_processes 1;

events {
    worker_connections 1024;
}

http {

    resolver 1.1.1.1 ipv6=off;

    server {

        listen 80;

        #
        # Model discovery
        #
        location = /v1/models {

            default_type application/json;

            return 200 '
{
  "data": [
    {
      "id": "claude-sonnet-4-8",
      "display_name": "Sonnet 4.8",
      "type": "model"
    }
  ]
}';
        }

        #
        # Chat
        #
        location = /v1/messages {

            rewrite_by_lua_block {

                local cjson = require "cjson.safe"

                ngx.req.read_body()

                local body = ngx.req.get_body_data()

                if body then

                    local json = cjson.decode(body)

                    if json and json.model then

                        local map = {
                            ["claude-sonnet-4-8"] = "MiniMax-M3",
                        }

                        json.model = map[json.model] or json.model

                        ngx.req.set_body_data(cjson.encode(json))
                    end
                end
            }

            proxy_ssl_server_name on;

            proxy_buffering off;
            proxy_request_buffering off;

            proxy_set_header Host api.minimax.io;

            proxy_set_header X-Api-Key $http_x_api_key;

            proxy_set_header anthropic-version $http_anthropic_version;
            proxy_set_header anthropic-beta $http_anthropic_beta;

            proxy_pass https://api.minimax.io/anthropic/v1/messages;
        }
    }
}
